q9f/eth.rb

Gemfile, lib/eth/utils.rb
bump `keccak` to 1.3.0; rename `::SHA3` to `::Keccak`
* ref https://github.com/q9f/keccak.rb/pull/16
bump `rbsecp256k1` to 5.1.0 to address M1 silicon issues
* ref https://github.com/etscrivner/rbsecp256k1/pull/55
=> gems: bump keccak and secp256k1

lib/eth.rb, lib/eth/address.rb, lib/eth/key.rb, spec/eth/address_spec.rb, spec/eth/key_spec.rb
The `Eth::Address` implementation contains two slight, yet important changes compared to the [original repo](https://github.com/se3000/ruby-eth/blob/develop/lib/eth/address.rb):
1. We are making `address` readable. The rationale is that a user could previously access `address` via the `checksummed` method, could check if an initialized `address` was `valid?`, but not access the initialized `address` itself. This leads to the next important change.
2. `Eth::Key::address` returns the entire `Eth::Address` object, rather than just a `checksummed` address hex. This is a breaking change compared to the original repo, but does give the user more visibility into the key/address relationship.
=> Address class implementation and tests

lib/eth/address.rb, lib/eth/key.rb, lib/eth/utils.rb, spec/eth/utils_spec.rb
removing the TODO
I think it's sensible to not return a string but rather provide access to the Address object.
=> eth/util: public_key_to_address should return an eth::address

lib/eth.rb, lib/eth/address.rb, lib/eth/chains.rb, lib/eth/signature.rb, spec/eth/chains_spec.rb, spec/eth/signature_spec.rb
ref #15 
`Eth::Signature.personal_recover message, signature, chain_id`
* moved from `Eth::Key` to `Eth::Signature` namespace because recovering Signatures work without known keys
* added support for chain IDs (EIP 155)
works entirely with `rbsecp256k1` (no openssl)
=> lib/signature: implement personal_recover (eip 191)

lib/eth/chains.rb, lib/eth/key.rb, lib/eth/signature.rb, spec/eth/key_spec.rb, spec/eth/signature_spec.rb
* `Eth::Key.personal_sign message, chain_id`
* `Eth::Signature.verify message, signature, public_key, chain_id`
=> key/signature: personal sign and verify

lib/eth/chain.rb, lib/eth/key.rb, spec/eth/chain_spec.rb, spec/eth/key_spec.rb
=> eth/key: allow chain_id empty for signing messages/data

AUTHORS.txt, lib/eth/abi.rb, lib/eth/abi/event.rb, spec/eth/abi/event_spec.rb, spec/eth/abi_spec.rb
This adds some additional higher level functionality to the existing low level log decoder I previously.
Now you can do something like this to process log data from a client.
```ruby
logs = infura.eth_get_transaction_receipt(tx_hash)["result"]["logs"]
Eth::Abi::Event.decode_logs(ERC20_ABI, logs).each do |raw_log, log|
if log && log.name == "Transfer"
puts log.kwargs[:from], "=>", log.kwargs[:to]
end
end
```
Maybe this example is worth adding to the README?
=> eth/abi/event: batch log decoder

README.md, lib/eth/client.rb, spec/eth/client_spec.rb, spec/fixtures/contracts/signer.sol
=> lib: method for eip-1271

eth.gemspec
fixes #87 
Eth.rb works with both 2.x and 3.x, gemspec needs a slight adjustment to allow for OpenSSL 2.2 and greater to be supported.
I've limited to anything less then OpenSSL 4.0 incase this included any breaking changes for the major update in the future.
=> Add dependency support for openssl 2.2 and greater, including 3.x (#87)

lib/eth/contract.rb
`constructor_inputs` when creating a contract `from_file` was missing.
We should probably enable passing constructor params with something like this:
```
def encode_constructor_params(contract, args)
types = contract.constructor_inputs.map { |input| input.type }
Util.bin_to_hex(Eth::Abi.encode(types, args))
end
```
as well, and appending it to `data` in `deploy` and `transact`.
Be happy to extend this PR if that's a direction we'd want to go.
=> Add missing def_delegator for constructor_inputs

lib/eth/abi.rb, spec/eth/abi_spec.rb
closes #98 
however, if a hexstring is not prefixed, it will be hard to determine whether it is a bytes string or not. we'll potentially see this popping up again.
=> eth/abi: fix handling of hex values for byte strings

lib/eth/client.rb, spec/eth/client_spec.rb
resolves https://github.com/q9f/eth.rb/issues/104
If raw result in call() is 0x, nil is returned.
=> Fix Eth::Abi::DecodingError in call method

lib/eth/client.rb, lib/eth/contract.rb, spec/eth/client_spec.rb, spec/eth/solidity_spec.rb, spec/fixtures/contracts/greeter.sol
=> Enable passing in constructor params to deploy

lib/eth/client.rb
I was receiving "intrinsic gas too low errors" while trying to deploy contracts with several constructor arguments. Upon inspection, I noticed that constructor argument data was not included in the intrinsic gas calculation. Including constructor data when computing the fee fixed the problem for me.
=> Include contract constructor args when estimating intrinsic gas

lib/eth/signature.rb, spec/eth/signature_spec.rb
Hi, thanks for the useful gem!
I encountered a problem when verifying signature signed with [web3.js](https://web3js.readthedocs.io/) that in some cases could not be verified correctly.
So I tried signing messages using web3.js and eth.rb, and noticed that different signatures are generated only if they contain multibyte characters.
Here is an example.
| message | signature (generated by web3.js) | signature (generated by eth.rb) |
| :-- | :-- | :-- |
| hello, ethereum! | 0x7b84abfdddd62aee9c598b98f74ae17b7b497b5530a92bd8f262ac33bccaed230fce76c74609e1c8c96b1bebe1a62e46477d3327481d8ed674d6c51bb98c689c1b | 0x7b84abfdddd62aee9c598b98f74ae17b7b497b5530a92bd8f262ac33bccaed230fce76c74609e1c8c96b1bebe1a62e46477d3327481d8ed674d6c51bb98c689c1b |
| こんにちは、イーサリアム! | …
=> eth/signature: fix prefix_message for multibyte characters

lib/eth/abi.rb, spec/eth/abi_spec.rb
There is no way to tell whether a string is a decimal, octal, hexadecimal, etc. 
Reverts q9f/eth.rb#112
=> eth/abi: raise error if numeric comes as string

lib/eth/client.rb, spec/eth/client_spec.rb
I've had some deployment failures due to running out of gas on deployment **when a constructor is invoked**. In some cases the intrinsic gas limit is off by a factor of 10. This change allows the developer to override the calculated model if necessary, without breaking the API.
=> Add gas limit override option for contract deployments

spec/eth/chain_spec.rb
I am afraid it is a small change.
It seems to be compatible with the Polygon chain, but I found a place where there is no test case, so I added it. Please check it.
=> chore: Add polygon chain test case

lib/eth/contract/function_input.rb, lib/eth/contract/function_output.rb, spec/eth/contract/function_input_spec.rb, spec/eth/contract/function_output_spec.rb
I have corrected the issues that were raised. Please check it if you would like to see it.
fix: #126
=> Fixed to return uint256[] correctly when passed as type

lib/eth/tx/eip1559.rb, lib/eth/tx/eip2930.rb, lib/eth/tx/legacy.rb, spec/eth/tx_spec.rb
Sometimes transaction can have "s" that has 62 char length, instead of 64 chars.
In the "ethereumjs-monorepo"(which is used in web3.js) used the same solution for creation signature
https://github.com/ethereumjs/ethereumjs-monorepo/blob/f39b0b2c826031a3f56b30f154d80c85bebfd611/packages/util/src/signature.ts#L59
```
const signature = Buffer.concat([setLengthLeft(r, 32), setLengthLeft(s, 32)], 64)
```
I've added the example transaction in tests:
```
Raw Transaction:
0xf86b820e8485012a05f200831e848094ffe811714ab35360b67ee195ace7c10d93f89d8c80844e71d92d8194a07b8f34a8fb85d850b3be4fc0330382e125e4216df5598c6d2c3bc47954684cf99f35ef53ee007c2f705eca91448b5c86e81d10f659ad868409bac8197bba9814
```
=> Fix Eth:Tx.decode for transaction with s length < 64 chars

lib/eth/client.rb, lib/eth/client/http_auth.rb, spec/eth/client_spec.rb
=> eth/client: rename http basic to http auth

lib/eth/client.rb, spec/eth/client_spec.rb
Sometimes we should have ability for send some non-zero value when we transact some action.
This PR give ability to make it.
close #137
=> Ability for call contract methods with specific transaction value was added

lib/eth/client.rb, spec/eth/client_spec.rb
Sometimes we need to replace already submitted pending tx, or plan our work with creating array of transactions to send, and it requires manual setting of nonce value. This PR give ability to set tx nonce manually.
=> Ability to manual set nonce of tx for transfer, deploy, transact methods was added.

lib/eth/client.rb
should close https://github.com/q9f/eth.rb/issues/141
=> Support camel case (convert before sending the tx)

lib/eth/client.rb, spec/eth/client_spec.rb
=> eth/client: add test for tx_succeeded?

lib/eth/client.rb, spec/eth/client_spec.rb
=> eth/client: dup params to prevent marshalling on client obj

.github/workflows/spec.yml, lib/eth/client.rb, spec/eth/client_spec.rb
if multiple overloads of a solidity function exist, this selects the correct one.
also adds an infura mainnet API to the spec tests.
=> eth/client: correctly select functions

spec/eth/contract_spec.rb, spec/fixtures/contracts/address_storage.sol
fix #143 
```ruby
geth = Client.create "/tmp/geth.ipc"
contract = Contract.from_file file: "spec/fixtures/contracts/address_storage.sol"
geth.deploy_and_wait contract
geth.call(contract, "retrieveMyAddress")
geth.transact_and_wait(contract, "storeMyAddress", Key.new.address.to_s)
geth.call(contract, "retrieveMyAddress")
geth.transact_and_wait(contract, "storeMyArray", [Key.new.address.to_s, Key.new.address.to_s])
geth.call(contract, "retrieveMyArray", 0)
geth.call(contract, "retrieveMyArray", 1)
```
=> eth/contract: ensure address arrays support

README.md, lib/eth/client.rb, spec/eth/client_spec.rb, spec/fixtures/contracts/deposit.sol, spec/fixtures/contracts/erc20.sol
```ruby
geth = Client.create "/tmp/geth.ipc"
erc = Contract.from_file(file: "spec/fixtures/contracts/erc20.sol")
geth.deploy_and_wait(erc, "FooBar", "FOO")
key = Key.new
geth.transfer_and_wait(key.address.to_s, 1 * Unit::ETHER)
geth.transact_and_wait(erc, "mint", key.address.to_s, 1 * Unit::ETHER)
geth.call(erc, "balanceOf", key.address.to_s)
geth.transfer_erc20_and_wait(erc, "0x49eB8f597De9B22D9141392d287BAfDc80994D51", 1, sender_key: key)
geth.call(erc, "balanceOf", key.address.to_s)
geth.call(erc, "balanceOf", "0x49eB8f597De9B22D9141392d287BAfDc80994D51")
```
fix #145
=> eth/client: add transfer_erc20 function

.github/workflows/spec.yml
Ruby 3.2 has been released.
Let's try WASM support and more!
https://www.ruby-lang.org/en/news/2022/12/25/ruby-3-2-0-released/
=> Tested with Ruby 3.2

lib/eth/abi/decoder.rb, spec/eth/abi_spec.rb
Before
```
> enc = Eth::Abi.encode ["string[]"], [["This is", "a test"]]
=> "\x00\x00\...
> Eth::Abi.decode ["string[]"], enc
.../gems/eth-0.5.10/lib/eth/abi.rb:232:in `decode_type': Wrong data size for string/bytes object (Eth::Abi::DecodingError)
```
After
```
> enc = Eth::Abi.encode ["string[]"], [["This is", "a test"]]
=> "\x00\x00\...
> Eth::Abi.decode ["string[]"], enc
=> [["This is", "a test"]]
```
=> Abi.decoder handles arrays of string and bytes

lib/eth/client.rb
For remote connection, there is no `Client.default_account` that can be automatically set. However, we are able to define it manually through `Client.default_account=`. This removed the error message and allow calling `Client.default_account` after it was manually set
=> Manual default_account

lib/eth/contract.rb
=> eth/contract: ensure contract name is title case

lib/eth/tx/eip1559.rb, lib/eth/tx/eip2930.rb, lib/eth/tx/legacy.rb, spec/eth/tx_spec.rb
Currently, the transaction decoding methods (both for EIP-1559 and EIP-2930) try to recover a sender address for unsigned transactions, which results in the following error:
```
lib/eth/chain.rb:161:in `+': nil can't be coerced into Integer (TypeError)
v = 2 * chain_id + 35 + recovery_id
^^^^^^^^^^^
```
This PR fixes this issue by checking if `recovery_id` is present.
=> Fix the decoding of unsigned transactions

lib/eth/eip712.rb, spec/eth/eip712_spec.rb
=> eth/eip721: fix data type bug for bytes, fix #251

spec/eth/contract_spec.rb
=> Fix typo in contract_spec.rb

.github/workflows/spec.yml, lib/eth/api.rb, lib/eth/client.rb, spec/eth/solidity_spec.rb
the api will be removed in geth 1.14.x
=> eth/api: remove coinbase as default account

lib/eth/client.rb, spec/eth/client_spec.rb
I know that this solution isn't ideal, and there is probably an easier approach. But it works, at least for me. Any support for custom block numbers would be great.
=> Allow to call JSON RPC with custom block number

lib/eth/tx/eip1559.rb, lib/eth/tx/eip2930.rb
I think the line `raise_error DecoderError, "Cannot decode EIP-2930 payload!"` was intended to be `raise DecoderError, "Cannot decode EIP-2930 payload!"` but didn't make it due to an accidental copy-paste from rspec.
`raise_error` isn't defined anywhere in the project and so this line currently doesn't work. Switching to `raise` will make it work as expected.
=> Fix undefined method `raise_error' for an instance of Eth::Tx::Eip1559 (NoMethodError)

lib/eth/util.rb, spec/eth/util_spec.rb
fix single-byte hex-string nibbles:
```ruby
[1] pry(main)> Util.hex_to_bin "a"
=> "\n"
[2] pry(main)> Util.bin_to_hex "\n"
=> "0a"
[3] pry(main)> Util.bin_to_hex Util.hex_to_bin "a"
=> "0a"
```
this fixes the bug raised in #292 
```ruby
[1] pry(main)> Rlp.encode "a"
=> "a"
[2] pry(main)> Rlp.decode "a"
=> "\n"
[3] pry(main)> Rlp.decode Rlp.encode "a"
=> "\n"
[4] pry(main)> Util.bin_to_hex Rlp.decode Rlp.encode "a"
=> "0a"
```
=> eth/util: fix single-byte hex-string nibbles

spec/eth/tx/eip1559_spec.rb
The describe blocks in the 1559 spec were all sitting under the initialize block, which seems like not the intended structure (especially when comparing with other specs).  This provides the minimal change for this and another minor whitespace comment change for consistency.  The diff below looks way scarier than the change is -- essentially there is an end block that is moved from the end of the file to before the .sign describe block and then the corresponding whitespace changes.
=> Updated nesting of describe blocks in the EIP-1559 spec.

spec/eth/client_spec.rb
Move the tests that are failing due to a geth upgrade to pending so they can be resolved and tracked without blocking other changes.
Related to #329
=> Move the tests that are failing due to a geth upgrade to pending 

lib/eth/tx/eip1559.rb, lib/eth/tx/eip2930.rb, lib/eth/tx/eip7702.rb, lib/eth/tx/legacy.rb
- correct `receiver` option descriptions in transaction classes
=> Fix receiver option spelling

lib/eth/util.rb
- Ensure int_to_big_endian initializes `hex` for numeric and hex string inputs
=> Handle hex input consistently in int_to_big_endian

lib/eth/util.rb
- correct `hex?` documentation to state it checks for hexadecimal strings
- document return value for `hex?` as `MatchData` or `nil`
=> docs(util): fix hex? return type

lib/eth/abi.rb, lib/eth/client.rb, lib/eth/contract.rb, lib/eth/contract/function.rb, spec/eth/contract/function_spec.rb, spec/eth/contract_spec.rb
In my case, I need to mock `eth_call` RPC requests, so I need to encode call args and decode call result to be public functions.
=> Add methods to encode function call and decode its result

lib/eth/util.rb, spec/eth/util_spec.rb
- allow `Util.int_to_big_endian` to accept prefixed and unprefixed hex strings
- test hex string support for `Util.int_to_big_endian`
=> Handle hex string inputs in big-endian conversion

CHANGELOG.md, lib/eth/client.rb, lib/eth/contract.rb, lib/eth/contract/error.rb, spec/eth/contract/error_spec.rb, spec/eth/custom_error_spec.rb
- add RpcError for rich RPC error info and decode custom errors
- handle `error` ABI entries and provide decoder
- cover decoding of custom errors in tests
=> Support Solidity custom errors per ERC-6093

lib/eth/client.rb, lib/eth/contract.rb, spec/eth/contract/error_spec.rb
- move error decoding logic into `Eth::Contract#decode_error`
- delegate error handling in `Eth::Client` to the contract
- add spec for `Contract#decode_error`
=> Move error decoding to contract module

README.md, lib/eth/tx/eip1559.rb, lib/eth/tx/eip2930.rb, lib/eth/tx/eip4844.rb, lib/eth/tx/eip7702.rb, lib/eth/tx/legacy.rb, spec/eth/tx/eip1559_spec.rb, spec/eth/tx/eip2930_spec.rb, spec/eth/tx/eip4844_spec.rb, spec/eth/tx/eip7702_spec.rb, spec/eth/tx/legacy_spec.rb
- support applying externally produced signatures to transactions
- document how to sign via remote key providers
- test external signature workflow for EIP-1559 and legacy transactions
fix #316
=> Allow signing transactions with external signatures

lib/eth/abi/decoder.rb, lib/eth/abi/encoder.rb, lib/eth/abi/type.rb, spec/eth/abi/event_spec.rb, spec/eth/abi/type_spec.rb, spec/eth/abi_spec.rb
- allow tuple ABI encoding with array args and handle nested tuples
- support decoding arrays of tuples and nested dynamic components
- parse canonical tuple syntax
- coerce numeric strings for integer/fixed types and enable ethers.js vectors
- guard decoder offsets for malformed tuple data
- fix #102
=> Add tuple array ABI support

spec/eth/abi/decoder_spec.rb, spec/eth/abi/encoder_spec.rb
- test decoding static arrays with dynamic items
- ensure encoder tuple rejects non collections
- cover number coercion helpers for encoder
- fix #371
=> Add tests for decoder static arrays and encoder helpers

lib/eth/abi/encoder.rb
Generally, Rubyist prefers symbolic hash keys, but in this gem we use string keys.
=> fix: transform hash keys to strings in encoder for component type compatibility
