- lib/eth.rb
- lib/eth/chains.rb
- spec/eth/chains_spec.rb
> eth/chains: implement eip 155 for replay protection

- .gitignore
- Gemfile
- lib/eth.rb
- lib/eth/abi.rb
- lib/eth/eip712.rb
- lib/eth/key.rb
- lib/eth/signature.rb
- lib/eth/unit.rb
- lib/eth/util.rb
- spec/eth/eip712_spec.rb
- spec/eth/key_spec.rb
- spec/eth/signature_spec.rb
- spec/eth/unit_spec.rb
ref https://github.com/se3000/ruby-eth/issues/44
fix #15
> signature: implement eip 712 typed structured data signing

- AUTHORS.txt
- Gemfile
- lib/eth/key.rb
- lib/eth/key/decrypter.rb
- lib/eth/key/encrypter.rb
- spec/eth/key/decrypter_spec.rb
- spec/eth/key/encrypter_spec.rb
- spec/fixtures/keys/testingtesting.json
- spec/fixtures/keys/testpassword.json
- spec/fixtures/keys/testunknownkdf.json
- Working with pbkdf2 derivation function
- Working with scrypt derivation function
- Tests to verify supported derivation function
- Added self as contributor
fix #14
> Implement encrypt/decrypt

- lib/eth/key.rb
- lib/eth/signature.rb
- spec/eth/signature_spec.rb
- spec/eth/tx_spec.rb
> eth/sig: allow v values > 0xff, fix #30

- eth.gemspec
> gem: relax openssl requirement

- lib/eth/client.rb
> eth/client: fix legacy transfer

- lib/eth/tx.rb
- lib/eth/tx/eip1559.rb
- lib/eth/tx/eip2930.rb
- lib/eth/tx/legacy.rb
> eth/tx: properly serialize signatures

- lib/eth/chain.rb
- lib/eth/client.rb
- lib/eth/tx.rb
- spec/eth/client_spec.rb
- spec/eth/tx/eip1559_spec.rb
- spec/eth/tx/eip2930_spec.rb
- spec/eth/tx/legacy_spec.rb
- spec/eth/tx_spec.rb
> eth/client: fix api documentation

- lib/eth/client.rb
I was seeing issues similar to those described in #141 . Upon looking at the call_raw method and cross referencing the documentation at https://ethereum.org/en/developers/docs/apis/json-rpc/#eth_call I noticed some discrepancies and simplified the method.
Some client nodes are lenient with extra params or the casing convention, while others are not.
> Remove invalid parameters from call_raw method

- lib/eth/client.rb
Adding a method to check if transaction has succeeded.
Also took the opportunity to change the name of `is_mined_tx?` -> `tx_mined?` to be closer to Ruby conventions (boolean methods with `?` without `is_`)
> add `tx_succeeded?`

- lib/eth/client.rb
- spec/eth/client_spec.rb
- spec/eth/solidity_spec.rb
- spec/fixtures/contracts/dummy.sol
> eth/client: raise an error if a contract interaction reverts

- lib/eth/client.rb
- lib/eth/client/http.rb
- lib/eth/client/http_auth.rb
- lib/eth/client/ipc.rb
> eth/client: rewrite send to send_request

- lib/eth/util.rb
- spec/eth/util_spec.rb
> eth/util: fix compressed public key to address

- eth.gemspec
https://github.com/etscrivner/rbsecp256k1/pull/77
> deps: update secp256k1 to 6

- eth.gemspec
- lib/eth/contract.rb
> deps: require forwardable for contracts

- lib/eth/client.rb
- spec/eth/client_spec.rb
> eth/client: remove default gas limit attribute

- .github/workflows/codeql.yml
- .github/workflows/docs.yml
- .github/workflows/spec.yml
> ci: update ruby version

- lib/eth/abi/decoder.rb
- lib/eth/abi/event.rb
- lib/eth/abi/type.rb
- lib/eth/contract/event.rb
- spec/eth/abi/event_spec.rb
- spec/eth/contract/event_spec.rb
* fix the event signature generated
> Support tuple params in EventLog

- lib/eth/abi/decoder.rb
- lib/eth/abi/encoder.rb
- spec/eth/abi_spec.rb
The solution for issue which is described here: https://github.com/q9f/eth.rb/issues/236
> Support negative number from JSON RPC

- lib/eth/abi/encoder.rb
- spec/eth/abi/encoder_spec.rb
- spec/eth/abi_spec.rb
- spec/eth/client_spec.rb
> eth/abi: fix negative integer *coding

- lib/eth/address.rb
- spec/eth/address_spec.rb
> eth/address: rename null address to zero address

- spec/eth/client_spec.rb
> spec/client: fix nonce too low error handling in spec

- lib/eth/abi/event.rb
- lib/eth/address.rb
- lib/eth/chain.rb
- lib/eth/contract/event.rb
- lib/eth/tx.rb
- lib/eth/tx/eip7702.rb
- spec/eth/chain_spec.rb
- spec/eth/contract/event_spec.rb
cleanup some previous work:
- document everything 100%
- add HOODI testnet chain ID `560048`
- fix contract event formatting
- raise NotimplementedError for EIP-4844
- supply documentation for EIP-7702 authorization lists
- supply unit tests for contract event parsing
> chore: run rufo, add docs

- CHANGELOG.md
- README.md
- lib/eth/tx.rb
- lib/eth/tx/eip4844.rb
- spec/eth/tx/eip4844_spec.rb
- add transaction type 0x3 for EIP-4844 shard-blob transactions
- support blob gas fee and versioned hashes in transaction handling
- document EIP-4844 support and add tests
fix #322
> feat: add eip-4844 transactions

- Gemfile
- update bundler to ~> 2.7
- bump simplecov-cobertura to ~> 3.0
> chore: update development dependencies
